# Generated by Django 4.0.1 on 2022-02-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_priority_task_status_changelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelog',
            old_name='current_state',
            new_name='diff',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='prev_state',
        ),
    ]
